FROM node:latest
RUN mkdir -p /usr/src/app/s-union
WORKDIR /usr/src/app/s-union
COPY package.json /usr/src/app/s-union
RUN npm install
COPY . /usr/src/app/s-union
EXPOSE 3000
CMD ["npm", "start"]

