'use strict';
const MESSAGE = {
  LOGIN_FAIL: 'Đăng nhập thất bại! Vui lòng kiểm tra lại!',
  SERVER_ERROR: 'Internal Server Error',
  CREATE_FAIL: 'Tạo dữ liệu thất bại! Vui lòng kiểm tra lại dữ liệu',
  CREATE_SUCCESS: 'Tạo dữ liệu thành công!',
  UPDATE_FAIL: 'Cập nhật thất bại! Vui lòng kiểm tra dữ liệu.',
  UPDATE_SUCCESS: 'Cập nhật dữ liệu thành công',
  DELETE_SUCCESS: 'Xóa dữ liệu thành công',
  DELETE_FAIL: 'Xóa dữ liệu thất bại! Vui lòng kiểm tra lại dữ liệu',
  NO_TOKEN: 'Không có dữ liệu token!',
  INVALID_TOKEN: 'Token không hợp lệ!',
  EMPTY_DATA: 'Không tìm thấy dữ liệu',
  EXISTED_DATA: 'Dữ liệu đã tồn tại',
  EXISTED_NAME: 'Tên đã tồn tại, vui lòng chọn tên khác',
  INVALID_DATA: 'Dữ liệu không hợp lệ!',
  EMPTY_DATA_UPDATE: 'Không tìm thấy dữ liệu cần cập nhật.',
  EMPTY_DATA_CONFIRM: 'Không tìm thấy dữ liệu cần xác nhận',
  NO_PERMISSION: 'Không có quyền truy cập tính năng này',
  CONFIRM_SUCCESS_UNION_TEXTBOOK: 'Xác nhận nộp sổ đoàn thành công',
  CONFIRM_FAIL_UNION_TEXTBOOK: 'Xác nhận nộp sổ đoàn thất bại',
  CONFIRM_SUCCESS_UNION_FEE: 'Xác nhận nộp đoàn phí thành công',
  CONFIRM_FAIL_UNION_FEE: 'Xác nhận nộp đoàn phí thất bại',
  OPEN_REGISTRATION_SUCESSFULLY: 'Mở đăng ký hoạt động thành công',
  OPEN_REGISTRATION_FAIL: 'Mở đăng ký hoạt động thất bại',
  CLOSE_REGISTRATION_SUCESSFULLY: 'Đóng đăng ký hoạt động thành công',
  CLOSE_REGISTRATION_FAIL: 'Đóng đăng ký hoạt động thất bại',
  REGISTER_SUCCESSFULLY: 'Đăng ký thành công',
  REGISTER_FAIL: 'Đăng ký thất bại',
  ATTEND_SUCCESSFULLY: 'Điểm danh thành công',
  ATTEND_FAIL: 'Điểm danh thất bại',
};

module.exports = MESSAGE;